name: notes
description: Firebase notes app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.2.0
  bloc: ^8.1.2
  cloud_firestore: ^4.7.1
  collection: ^1.17.2
  dartz: ^0.10.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_database: ^10.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  formz: ^0.6.0
  get_it: ^7.6.0
  google_sign_in: ^6.1.1
  great_list_view: ^0.2.3
  hydrated_bloc: ^9.1.1
  injectable: ^2.1.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  line_awesome_flutter: ^2.0.0
  meta: ^1.9.1
  path: ^1.8.3
  path_provider: ^2.0.15
  rxdart: ^0.27.7
  url_strategy: ^0.2.0
  uuid: ^3.0.7

dev_dependencies:
  auto_route_generator: ^7.1.1
  bloc_test: ^9.1.2
  build_runner: ^2.4.4
  dartz_test: ^0.1.1
  fake_cloud_firestore: ^2.4.1+1
  firebase_auth_mocks: ^0.11.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1

dependency_overrides:
  collection: ^1.17.2
  intl: ^0.18.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    
