// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzSu6sY6g0t_3GT_d1hOVcdqgkHG2uUdQ',
    appId: '1:427343878976:web:ff46d324147009a846f8a5',
    messagingSenderId: '427343878976',
    projectId: 'notes-64c3c',
    authDomain: 'notes-64c3c.firebaseapp.com',
    storageBucket: 'notes-64c3c.appspot.com',
    measurementId: 'G-6BF9T92F69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG1Ig7duhz8bUa_mDwKLEmawfha-QBGmU',
    appId: '1:427343878976:android:af9c9964f336e0ec46f8a5',
    messagingSenderId: '427343878976',
    projectId: 'notes-64c3c',
    storageBucket: 'notes-64c3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwrAkkiZ-N_x9sJPopS9uAtQuUqxwbWw0',
    appId: '1:427343878976:ios:9cb2301fbc12d32646f8a5',
    messagingSenderId: '427343878976',
    projectId: 'notes-64c3c',
    storageBucket: 'notes-64c3c.appspot.com',
    androidClientId: '427343878976-als19b4ch278i2pcrlb5s3pk9ch9i872.apps.googleusercontent.com',
    iosClientId: '427343878976-2sloc4j2fsnsqmuprnqs2qriuqmko3no.apps.googleusercontent.com',
    iosBundleId: 'com.codesynth.notes',
  );
}
